const receiptArr = [ 
    {
        person:"Karolin",
        order:{
                main:"Burrito",
                protein:"Organic Tofu",
                rice:"Purple Rice",
                sauce:"Green Crack",
                drink:"Korchata",
                cost:"22",
            },
        paid:"false"
    },
    {
        person:"",
        order:{
                main:"",
                protein:"",
                rice:"",
                sauce:"",
                drink:"",
                cost:"",
            },
        paid:""
    },
    {
        person:"",
        order:{
                main:"",
                protein:"",
                rice:"",
                sauce:"",
                drink:"",
                cost:"",
            },
        paid:""
    },
    {
        person:"",
        order:{
                main:"",
                protein:"",
                rice:"",
                sauce:"",
                drink:"",
                cost:"",
            },
        paid:""
    },
    {
        person:"",
        order:{
                main:"",
                protein:"",
                rice:"",
                sauce:"",
                drink:"",
                cost:"",
            },
        paid:""
    },
]
export default receiptArr;